### ISSUE TITLE
FastLED not working with ESP8266 (nodeMCU V1.0)

### ISSUE THREAD

**Issue by JIP0815** [TheAustrian/ESP8266-LED-Websockets#3]
Hi,
first of all I want to thank you for this amazing project.
When trying to compile it with Arduino 1.6.8 it only gave errors like this:
`Arduino\libraries\FastLED-3.1.0/platforms.h:22:2: error: #error "XTENSA-architecture`
microcontrollers are not supported"
Do you have any ideas how to fix this?
May you can make some screenshots of you Board settings and write a short documentation about your project?
Cheers,
JIP0815

**Comment by TheAustrian** [comment]
Hi! It seems that the 3.1 version had some glitch with ESP8266, see https://github.com/FastLED/FastLED/issues/289 - you might need to re-download the library in the latest version as suggested in the issue linked.

I'm currently also trying out a version with Neopixelbus instead of FastLed, since it runs more stable if I keep the lamp turned on for days I found (it uses DMA instead of the software bitbanging the FastLed library uses), but I haven't really had time to change all the code yet and it doesn't provide most of the convenience you get with FastLed. I'll upload the code when I'm done changing it.

The setup I use is quite easy and looks good from the outside, but it's not super-pretty inside, since I used an old iPad charger as power source, which added some bulk to the project. I'll make some pics and link them this weekend, but wiring is quite straightforward (1 data wire and 1 ground and 1 5V wire to the ESP and the LEDs each - as well as a bulky capacitor between ground and 5V, which I don't think is really necessary).

**Comment by JIP0815** [comment]
Thank you for the quick response.

> Hi! It seems that the 3.1 version had some glitch with ESP8266, see FastLED/FastLED#289 - you might need to re-download the library in the latest version as suggested in the issue linked. 

Compiling works fine with the head of the latest master version. Unfortunately my ESP8266 getting a bootloop now. In serial monitor it says:
`ets Jan  8 2013,rst cause:4, boot mode:(3,7)`
`wdt reset`
`load 0x4010f000, len 1264, room 16`
`tail 0`
`chksum 0x0f`
`csum 0x0f`
`~ld`
Do you know this kind of bug?

Btw. my setup is quite similar to yours. Having an WS2812b strip with 60 LEDs connected to an 2A USB-charger. A level shifter converts the signal to 5.5V for the strip. A capacitor smooths the 5V from the charger to prevent current peaks. This setup work fine with a RPi and Arduino Nano V3.

**Comment by TheAustrian** [comment]
It's a watchdog timer reset. If it happens on startup you are probably staying too long in the setup function or running a tight loop somewhere without using delay() or yield().

**Comment by JIP0815** [comment]
> It's a watchdog timer reset. If it happens on startup you are probably staying too long in the setup function or running a tight loop somewhere without using delay() or yield().

Tried it with uncommenting it in your code and change the delays, but nothing really works.
Seems to be a problem with FastLED. When LEDS.addLeds<...>(...) is called the controller restarts.

**Comment by TheAustrian** [comment]
Ok, you might want to also post this issue at the FastLed library page then so they can have a look at it.
https://github.com/FastLED/FastLED/issues
